#! /bin/sh

### AUTOSTART PROGRAMS ###

if [[ hostname = "two-face" ]]
then
	~/.config/dotfiles/scripts/two-face.sh &
fi
~/.config/polybar/launch.sh &
sxhkd &
nitrogen --restore &

### MONITORS AND WORKSPACES ###

#PC
bspc monitor DP-0 -d I II III IV V VI VII VIII IX 
bspc monitor DP-2 -d I II III IV V VI VII VIII IX

#Laptop
bspc monitor eDP1 -d I II III IV V VI VII VIII IX

### BSPWM CONFIG ###

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

